server:
  port: 8188
  servlet:
    context-path: /web-market-auth
#spring:
#  datasource:
#    url: 'jdbc:postgresql://localhost:5433/postgres'
#    username: 'postgres'
#    password: 'postgres'
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: 'andreyzorin494'
    password: 'GeekBrains'
    properties:
      mail:
        smtp:
          auth: 'true'
          starttls:
            enable: 'true'
jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g
  lifetime: 36000000
