server:
  port: 8166
  servlet:
    context-path: /web-market-carts
utils:
  cart:
    prefix: SPRING_WEB_APP_
  statistic:
    key: CART_STATISTICAL_KEY
    clear-cron: 0 0 0 * * *
    add-cron: 0 10 * * * *
  identity-map:
    clear-cron: 0 0 0 * * *
integrations:
  core-service:
    url: http://localhost:5555/core
    connect-timeout: 2000
    read-timeout: 10000
    write-timeout: 2000
    response-timeout: 2000
#spring:
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true