server:
  port: 8189
  servlet:
    context-path: /web-market-core
utils:
  cart:
    prefix: SPRING_WEB_
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5434/azor-shop-spring-rest-core
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.PostgreSQLDialect
integrations:
  cart-service:
    url: http://localhost:5555/cart
    connect-timeout: 2000
    read-timeout: 10000
    write-timeout: 2000
